#!/usr/bin/env python

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation


#Warning Orocos Reporting component leaves space on last line. Delete it before reading log.(@IndexError: list of index out of range)
f = open('/home/mlotz/orocosPoligon/reports.dat', 'r')
lines = f.readlines()
f.close

timestamp = []
x = []
y = []
z = []
wx = []
wy = []
wz = []


once = 0

for line in lines:
	if (once == 0):
		once = 1
		continue
	p = line.split()
	#print str(p[0])
	timestamp.append(float(p[0]))
	x.append(float(p[1]))
	y.append(float(p[2]))
	z.append(float(p[3]))
	wx.append(float(p[8]))
	wy.append(float(p[9]))
	wz.append(float(p[10]))


tv = np.array(timestamp)
xv = np.array(x)
yv = np.array(y)
zv = np.array(z)
twx = np.array(wx)
twy = np.array(wy)
twz = np.array(wz)

fig1= plt.figure()
plt.plot(tv,yv)
plt.title('x over time', fontsize=20)
plt.xlabel('time[s]')
plt.ylabel('x[m]')
fig2= plt.figure()
plt.plot(tv,xv)
plt.title('y over time', fontsize=20)
plt.xlabel('time[s]')
plt.ylabel('y[m]')
fig3= plt.figure()
plt.xlabel('time[s]')
plt.ylabel('z[m]')
plt.title('z over time', fontsize=20)
plt.plot(tv,zv)

fig3ipol= plt.figure()
plt.xlabel('time[s]')
plt.ylabel('Fxy[N]')
plt.title('Fxy over time', fontsize=20)
plt.plot(tv,np.sqrt((twx*twx)+(twy*twy)))


fig4= plt.figure()
plt.xlabel('y[m]')
plt.ylabel('x[m]')
plt.title('end effector trajectory on XY plane', fontsize=20)
plt.axis('equal')
plt.scatter(xv,yv)
#fig1= plt.figure()
#plt.plot(tv,xv)
#plt.plot(tv,yv)
#plt.plot(tv,zv)
#fig2= plt.figure()
#plt.axis('equal')
#plt.scatter(xv,yv)

plt.show()



